[project]
name = "federicov-github-io"
version = "0.1.0"
description = "Federico's Blog - built with Pelican"
requires-python = ">=3.11"
dependencies = [
    "ghp-import>=2.1.0",
    "markdown>=3.10",
    "pelican>=4.11.0.post0",
    "pelican-render-math>=1.0.5",
    "typogrify>=2.1.0",
]
